name: AuTerm build (Linux)

on: workflow_dispatch

jobs:
  auterm-build-linux:
    name: build-steps
    runs-on: [self-hosted, "Windows"]
    if: github.actor == 'thedjnK'
    steps:
    - name: build-auterm
      shell: cmd
      run: |
        E:\github\__build_scripts\build_linux.bat ${{ secrets.SENSITIVE_LINUX }} main
    - name: upload-auterm
      uses: actions/upload-artifact@v4
      with:
        name: AuTerm-Linux
        path: AuTerm_*.tar.gz
