name: AuTerm build (mac)

on: workflow_dispatch

jobs:
  auterm-build-mac:
    name: build-steps
    runs-on: macos-13
    if: github.actor == 'thedjnK'
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        repository: thedjnK/AuTerm
        ref: main
        fetch-depth: 1
        fetch-tags: false
    - uses: actions/download-artifact@v4
      with:
        name: toolchain
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: 12381615845
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: build-auterm
      run: |
        # xcode 15.2 is broken, xcode 15.1 is broken, use 14.3
        sudo xcode-select -switch /Applications/Xcode_14.3.app
        sudo tar -xf qt6.8.1-static-mac.tar.gz -C /
        /usr/local/Qt/6.8.1-static/bin/qmake6 -config release
        make -j4
        version=$(cat AuTerm/AutMainWindow.h  | grep "const QString UwVersion" | cut -d "\"" -f 2)
        cd release
        tar -czf ../AuTerm_test_Mac_x64_arm64_v$version.tar.gz AuTerm.app/
        git rev-parse HEAD
    - name: upload-auterm
      uses: actions/upload-artifact@v4
      with:
        name: AuTerm-mac
        path: AuTerm_test_Mac_x64_arm64_v*.tar.gz
