name: qtmgmt build (Linux)

on: workflow_dispatch

jobs:
  qtmgmt-build-linux:
    name: build-steps
    runs-on: [self-hosted, "Windows"]
    if: github.actor == 'thedjnK'
    steps:
    - name: build-qtmgmt
      shell: cmd
      run: |
        E:\github\__build_scripts\build_qtmgmt_linux.bat ${{ secrets.SENSITIVE_LINUX }} main
    - name: upload-qtmgmt
      uses: actions/upload-artifact@v4
      with:
        name: qtmgmt-Linux
        path: qtmgmt_*.tar.gz
